nice-digital/MAS

- cms/models/Item.js
https://nicedigital.atlassian.net/browse/MAS-108
> MAS-108 Add core fields

- cms/models/Item.js
https://nicedigital.atlassian.net/browse/MAS-108?focusedCommentId=33027&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-33027
> MAS-108 Core fields Keystone models

- cms/models/Item.js
https://nicedigital.atlassian.net/browse/MAS-141
> MAS-141 Add URL as a field to CMS

- cms/models/Item.js
- cms/public/styles/keystone.less
- package-lock.json
https://nicedigital.atlassian.net/browse/MAS-149
> MAS-149 Small changes after demo

- cms/models/Item.js
- lambda/MAS/Models/Item.cs
https://nicedigital.atlassian.net/browse/MAS-159
> MAS-000 Fix 500 Error

- cms/MAS.CMS.nuspec
- cms/package-lock.json
- cms/package.json
https://nicedigital.atlassian.net/browse/MAS-179
> MAS-179 Add nuspec for the CMS package

- functional-tests/steps/then.js
https://nicedigital.atlassian.net/browse/MAS-188
> MAS-188 - Fix team city automated tests

- lambda/MAS/Controllers/ContentController.cs
https://nicedigital.atlassian.net/browse/MAS-189
> MAS-189 Add logging to lambda when S3 write fails

- nginx.conf
- static-assets/404.html
- static-assets/app.css
https://nicedigital.atlassian.net/browse/MAS-185
> MAS-185 Add 404 page to static website

- cms/Dockerfile
- cms/keystone.js
- cms/package-lock.json
- cms/package.json
- docker-compose.yml
https://nicedigital.atlassian.net/browse/MAS-186
> MAS-186 Move sessions to Mongo

- static-assets/robots.txt
https://nicedigital.atlassian.net/browse/MAS-195
> MAS-195 Add robots txt file for static site with Octo variable

- functional-tests/features/editFields.feature
- functional-tests/steps/then.js
- functional-tests/steps/when.js
- functional-tests/support/action/click.js
https://nicedigital.atlassian.net/browse/MAS-198
> MAS-198 - added delete scenario plus fix flaky test

- cms/models/Source.js
https://nicedigital.atlassian.net/browse/MAS-204
> MAS-204 Change title to source name

- README.md
- lambda/MAS.Tests/UnitTests/LambdaEntryPointTests.cs
- lambda/MAS/LambdaEntryPoint.cs
- lambda/MAS/serverless.template
https://nicedigital.atlassian.net/browse/MAS-163
> MAS-163 Scheduling email sending

- lambda/MAS.Tests/Feeds/daily-items-2020-01-01.json
- lambda/MAS.Tests/Feeds/daily-items.json
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApproved.approved.txt
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApprovedForSingleItemWithSpecificDate.approved.txt
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.cs
- lambda/MAS/Configuration/MailConfig.cs
- lambda/MAS/Views/Mail/Daily.cshtml
- lambda/MAS/appsettings.json
https://nicedigital.atlassian.net/browse/MAS-210
> MAS-210 Put evidence types in specific order in daily emails

- cms/keystone.js
https://nicedigital.atlassian.net/browse/MAS-212
> MAS-212 MEC Formatting

- mailchimp-templates/weekly.html
- Change has been made in Mailchimp as of now
> MAS-000 Remove heading from mailchimp template

- mailchimp-templates/daily.html
- mailchimp-templates/weekly.html
Big changes to these files due to VSCode using prettier - use prettier where possible!
> MAS-224 Add COVID message to daily and weekly template

- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApproved.approved.txt
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApprovedForSingleItem.approved.txt
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApprovedForSingleItemWithSpecificDate.approved.txt
- lambda/MAS/Views/Mail/Daily.cshtml
https://nicedigital.atlassian.net/browse/MAS-218
> MAS-218 Articles without specialities showing in wrong place 

- lambda/MAS.Tests/Feeds/daily-items-2020-01-01.json
- lambda/MAS.Tests/Feeds/daily-items.json
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApproved.approved.txt
- lambda/MAS.Tests/IntegrationTests/DailyEmailTests.EmailBodyHtmlMatchesApprovedForSingleItemWithSpecificDate.approved.txt
- lambda/MAS/appsettings.json
These got changed in MAS-206 but weren't updated in app settings so the order on the email was off
> MAS-232 Updated names of broader evidence types

- cms/keystone.js
https://nicedigital.atlassian.net/browse/MAS-220
> MAS-220 Superscript characters keep formatting

- cms/__tests__/routes/api/items.test.js
- cms/keystone.js
https://nicedigital.atlassian.net/browse/STAK-14
> STAK-14 Update terminology

- cms/models/Weekly.js
https://nicedigital.atlassian.net/browse/MAS-236
> MAS-236 Allow Weekly title in Keystone to be edited

- cms/routes/middleware.js
https://nicedigital.atlassian.net/browse/MAS-239
Maybe no longer needed? https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/
> MAS-239 Opt out of FLoC
